id: I90FDA606
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:46:46.109969
last_modified: 2023-02-09 14:46:46.110076
source_metadata:
  title: 'PP: Prajñāpāramitāhṛdaya'
  language: zh
bases:
  25F3:
    base_file: 25F3.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
